In [60]:
#35.프로젝트 루트 설정

from pathlib import Path

project_root = Path.cwd()

if project_root.name == "notebooks":

    project_root = project_root.parent

data_dir = project_root / "data" / "raw"

print("프로젝트 루트:", project_root)

print("데이터 폴더:", data_dir)

print("데이터 폴더 존재:", data_dir.exists())

프로젝트 루트: c:\dev\ai-data-analysis
데이터 폴더: c:\dev\ai-data-analysis\data\raw
데이터 폴더 존재: True

In [61]:
# 36. pandas와 CSV 불러오기

import pandas as pd

customers = pd.read_csv(data_dir / "customers.csv")
products = pd.read_csv(data_dir / "products.csv")
orders = pd.read_csv(data_dir / "orders.csv")
order_items = pd.read_csv(data_dir / "order_items.csv")

In [62]:
# 37. 기본 구조와 주요 키 확인

datasets = {
    "customers": customers,
    "products": products,
    "orders": orders,
    "order_items": order_items,
}

for name, df in datasets.items():
    print(name, df.shape, df.columns.tolist())

customers (150, 6) ['customer_id', 'name', 'gender', 'age', 'city', 'signup_date']
products (100, 4) ['product_id', 'product_name', 'category', 'price']
orders (301, 5) ['order_id', 'customer_id', 'order_date', 'payment_method', 'order_status']
order_items (766, 5) ['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price']

In [63]:
key_checks = {
    "customers.customer_id": customers["customer_id"],
    "products.product_id": products["product_id"],
    "orders.order_id": orders["order_id"],
    "order_items.order_item_id": order_items["order_item_id"],
}

for name, series in key_checks.items():

    print(
        name,
        "결측:", series.isna().sum(),
        "중복:", series.duplicated().sum(),
    )

customers.customer_id 결측: 0 중복: 0
products.product_id 결측: 0 중복: 0
orders.order_id 결측: 0 중복: 0
order_items.order_item_id 결측: 0 중복: 1

In [64]:
# 38. Series와 DataFrame 선택

city_series = customers["city"]

customer_view = customers[
    ["customer_id", "gender", "age", "city"]
]
print(type(city_series))
print(type(customer_view))

display(customer_view.head())

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

   customer_id gender  age city
0            1      F   19   광주
1            2      F   32   대구
2            3      F   61   성남
3            4      F   55   울산
4            5      F   19   부산

In [65]:
# 39. 단일 조건 필터링

customers_over_30 = customers[
    customers["age"] >= 30
]
print(len(customers), len(customers_over_30))
display(customers_over_30.head())

150 111

   customer_id name gender  age city signup_date
1            2  김정호      F   32   대구  2025-11-29
2            3  이경수      F   61   성남  2024-07-09
3            4  조영호      F   55   울산  2026-05-10
5            6  김지원      F   32   성남  2026-07-24
6            7  이상현      F   53   인천  2025-01-08

In [66]:
# 40. 복합 조건 필터링

seoul_over_30 = customers[
    (customers["age"] >= 30)
    & (customers["city"] == "서울")
]
display(seoul_over_30.head())

    customer_id name gender  age city signup_date
8             9  송지민      M   69   서울  2025-11-15
14           15  장정식      M   69   서울  2026-07-01
29           30  이민재      F   32   서울  2023-08-10
47           48  김예은      F   47   서울  2025-04-28
65           66  김재호      F   39   서울  2025-12-30

In [67]:
# 서울 또는 부산:

seoul_or_busan = customers[
    customers["city"].isin(["서울", "부산"])
]

display(
    seoul_or_busan["city"].value_counts())

city
부산    16
서울    15
Name: count, dtype: int64

In [68]:
# 완료 주문이 아닌 주문 :

not_completed = orders[
    ~(orders["order_status"] == "completed")
]

display(
    not_completed["order_status"].value_counts(
        dropna=False
    )
)

order_status
cancelled    65
refunded     52
Name: count, dtype: int64

In [69]:
#41. 상품 가격 정렬

expensive_products = (
    products
    .sort_values("price", ascending=False)
    .head(10)
)

display(
    expensive_products[
        [
            "product_id",
            "product_name",
            "category",
            "price",
        ]
    ]
)

    product_id product_name category   price
98          99    뷰티 상품 099       뷰티  200000
69          70    패션 상품 070       패션  198000
57          58    식품 상품 058       식품  197000
42          43    뷰티 상품 043       뷰티  197000
23          24   스포츠 상품 024      스포츠  196000
8            9   스포츠 상품 009      스포츠  193000
36          37    뷰티 상품 037       뷰티  193000
71          72    뷰티 상품 072       뷰티  189000
7            8   스포츠 상품 008      스포츠  189000
52          53  생활용품 상품 053     생활용품  188000

In [70]:
#Part. line_total 생성과 전체 주문 금액 구분
#42. 작업용 복사본과 파생 컬럼
order_items_work = order_items.copy()

# 데이터 프레임에 새로운 컬럼을 추가할 때는 기존 컬럼을 활용한 연산을 수행할 수 있습니다.

order_items_work["line_total"] = (
    order_items_work["quantity"]
    * order_items_work["unit_price"]
)

In [71]:
print(order_items_work.head())

   order_item_id  order_id  product_id  quantity  unit_price  line_total
0              1         1         100         3      102000      306000
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000

In [72]:
display(
    order_items_work[
        [
            "order_item_id",
            "order_id",
            "product_id",
            "quantity",
            "unit_price",
            "line_total",
        ]
    ].head()
)

   order_item_id  order_id  product_id  quantity  unit_price  line_total
0              1         1         100         3      102000      306000
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000

In [73]:
# 43. 수작업 검증
sample = order_items_work.iloc[0]
expected = sample["quantity"] * sample["unit_price"]
actual = sample["line_total"]

print("수작업:", expected)
print("파생 컬럼:", actual)
print("일치:", expected == actual)

수작업: 306000
파생 컬럼: 306000
일치: True

In [74]:
# 45. 병합용 주문 컬럼 선택
orders_for_merge = orders[
    [
        "order_id",
        "customer_id",
        "order_date",
        "order_status",
    ]
].copy()

print(orders_for_merge.shape)
print(orders_for_merge.head())

(301, 4)
   order_id  customer_id  order_date order_status
0         1          123  2026-06-03    completed
1         2           77  2025-08-19    cancelled
2         3          138  2025-12-16    cancelled
3         4           57  2026-02-26    cancelled
4         5          125  2026-01-17    cancelled

In [75]:
# 46. 주문상세와 주문 병합
order_sales = (
    order_items_work
    #order_items와 뭐가 다른가? 커러럼이 다르다. order_items_work는 line_total이 추가된 상태
    .merge(
        orders_for_merge,
        on="order_id",
        how="left",
        validate="many_to_one",
        indicator="order_match",
    )
)

In [76]:
# 47. 병합 검증
# display란 무엇인가? display는 Jupyter Notebook에서 데이터를 시각적으로 표시하는 함수입니다.
# print와 달리 DataFrame이나 Series를 표 형태로 보여주며, HTML 렌더링을 지원합니다.
# 따라서 데이터의 구조와 내용을 더 직관적으로 확인할 수 있습니다.
print("병합 전 행 수:", len(order_items_work))
print("병합 후 행 수:", len(order_sales))
display(
    order_sales["order_match"].value_counts(
        dropna=False
    )
)

병합 전 행 수: 766
병합 후 행 수: 766

order_match
both          765
left_only       1
right_only      0
Name: count, dtype: int64

In [77]:
# 미매칭 확인:

unmatched_orders = order_sales[
    order_sales["order_match"] != "both"
]
display(unmatched_orders.head())

,order_item_id,order_id,product_id,quantity,unit_price,line_total,customer_id,order_date,order_status,order_match
764,789,320,67,5,32000,160000,NaN,NaN,NaN,left_only

In [78]:
# 48. 완료 주문 분석셋
display(
    order_sales["order_status"].value_counts(
        dropna=False
    )
)

order_status
completed    475
cancelled    162
refunded     128
NaN            1
Name: count, dtype: int64

In [79]:
completed_sales = order_sales[
    order_sales["order_status"] == "completed"
].copy()

completed_sales["customer_id"] = completed_sales["customer_id"].astype(int)

In [80]:

print("완료 주문상세 행:", len(completed_sales))
print(
    "완료 주문 수:",
    completed_sales["order_id"].nunique(),
)
print(
    "완료 주문 고객 수:",
    completed_sales["customer_id"].nunique(),
)
print(
    "완료 주문 매출:",
    completed_sales["line_total"].sum(),
)

#검증을 하는 이유는 데이터 분석에서 데이터의 정확성과 일관성을 확인하기 위해서입니다.
#병합 후 행 수, 미매칭 데이터, 완료 주문 수 등을 검증함으로써 데이터 처리 과정에서 
#발생할 수 있는 오류나 누락을 발견하고 수정할 수 있습니다.

완료 주문상세 행: 475
완료 주문 수: 184
완료 주문 고객 수: 100
완료 주문 매출: 149690000

In [81]:
# 49. 필요한 상품 정보만 선택
#프로덕트 파일에서 아이디, 이름, 카테고리만 선택하여 병합에 사용할 하겠다고 하는 의미입니다.
#copy()를 사용하는 이유는 원본 데이터프레임을 변경하지 않고 새로운 데이터프레임을 생성하기 위해서입니다.
products_for_merge = products[
    [
        "product_id",
        "product_name",
        "category",
    ]
].copy()

In [82]:
# 50. 완료 주문상세와 상품 병합
#completed_items로 만들어서 먼저 설정해 놓은 completed_sales와 products_for_merge를 병합합니다.
completed_items = (
    completed_sales
    .merge(
        products_for_merge,
        on="product_id",
        how="left",
        validate="many_to_one",
        indicator="product_match",
    )
)
#left란 무엇인가? left는 병합 시 기준이 되는 데이터프레임을 의미합니다.
#데이터 프레임이란? 2차원 표 형식의 데이터 구조로, left로 왼쪽 정렬을 의미합니다.

In [83]:
print(len(completed_sales), len(completed_items))
display(
    completed_items["product_match"].value_counts(
        dropna=False))

475 475

product_match
both          474
left_only       1
right_only      0
Name: count, dtype: int64

In [84]:
# 51. 카테고리별 매출

 

category_sales = (
    completed_items
    .groupby("category", as_index=False)
    .agg(
        total_sales=("line_total", "sum"),
        order_count=("order_id", "nunique"),
        customer_count=("customer_id", "nunique"),
        quantity_sold=("quantity", "sum"),
        detail_row_count=("order_item_id", "count"),
    )
    .sort_values("total_sales", ascending=False)
)
display(category_sales)

,category,total_sales,order_count,customer_count,quantity_sold,detail_row_count
3,스포츠,31743000,85,67,295,100
5,전자기기,26400000,60,44,259,78
2,생활용품,23915000,65,50,272,83
1,뷰티,23383000,65,53,223,76
4,식품,16573000,36,31,133,42
0,도서,16389000,52,46,149,58
6,패션,10587000,33,27,111,37

In [85]:
#52. 카테고리 합계 검증
# 카테고리 합계 검증을 하는 이유는 데이터 분석에서
# 카테고리별 매출 합계가 전체 매출과 일치하는지 확인하기 위해서입니다.
category_total = category_sales["total_sales"].sum()
completed_total = completed_items["line_total"].sum()

print(category_total)
print(completed_total)
print(category_total == completed_total)

148990000
149690000
False

In [86]:
#53. 상품별 매출
#nunique란 무엇인가? nunique는 pandas에서 고유한 값의 개수를 계산하는 함수입니다.
#sort_values란 무엇인가? sort_values는 pandas에서 데이터프레임을 특정 컬럼의 값에 따라 정렬하는 함수입니다.
product_sales = (
    completed_items
    .groupby(
        ["product_id", "product_name", "category"],
        as_index=False,
    )
    .agg(
        total_sales=("line_total", "sum"),
        quantity_sold=("quantity", "sum"),
        order_count=("order_id", "nunique"),
        customer_count=("customer_id", "nunique"),
    )
    .sort_values("total_sales", ascending=False)
)
display(product_sales.head(10))

,product_id,product_name,category,total_sales,quantity_sold,order_count,customer_count
39,41,스포츠 상품 041,스포츠,5705000,35,12,11
11,12,식품 상품 012,식품,4375000,25,7,7
8,9,스포츠 상품 009,스포츠,3860000,20,6,5
70,72,뷰티 상품 072,뷰티,3780000,20,6,6
69,71,전자기기 상품 071,전자기기,3703000,23,5,5
66,68,스포츠 상품 068,스포츠,3640000,26,8,8
78,81,전자기기 상품 081,전자기기,3630000,22,6,6
10,11,패션 상품 011,패션,3565000,31,7,7
20,22,생활용품 상품 022,생활용품,3248000,29,8,8
86,89,생활용품 상품 089,생활용품,3090000,30,11,11

In [87]:
#54. 주문 날짜 변환과 주문 월 생성
#order_date 컬럼을 datetime 형식으로 변환하는 이유는 데이터 분석에서 날짜와 시간 관련 연산을 수행하기 위해서입니다.
#변환 했을 때의 효과는 datetime 형식으로 변환하면 날짜와 시간 관련 연산, 필터링, 그룹화 등을 쉽게 수행할 수 있습니다.
# 왜냐하면 문자열 형식으로 되어 있는 날짜 데이터를 datetime 형식으로 변환하면 pandas에서 제공하는
# 다양한 날짜 관련 기능을 활용할 수 있기 때문입니다.
completed_items["order_date"] = pd.to_datetime(
    completed_items["order_date"],
    errors="coerce",
)
print(
    "날짜 변환 실패:",
    completed_items["order_date"].isna().sum(),
)

날짜 변환 실패: 0

In [88]:
completed_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 475 entries, 0 to 474
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  475 non-null    int64
 1   order_id       475 non-null    int64
 2   product_id     475 non-null    int64
 3   quantity       475 non-null    int64
 4   unit_price     475 non-null    int64
 5   line_total     475 non-null    int64
 6   customer_id    475 non-null    int64
 7   order_date     475 non-null    datetime64[us]
 8   order_status   475 non-null    str
 9   order_match    475 non-null    category
 10  product_name   474 non-null    str
 11  category       474 non-null    str
 12  product_match  475 non-null    category
dtypes: category(2), datetime64[us](1), int64(7), str(3)
memory usage: 59.6 KB

In [89]:
completed_items["order_month"] = (
    completed_items["order_date"]
    .dt.to_period("M")
    .astype("string")
)
#dt란 무엇인가? dt는 pandas에서 datetime 형식의 데이터를 다루기 위한 접근자입니다.
#datetime이란 무엇인가? datetime은 날짜와 시간을 나타내는 데이터 타입입니다.
#dt.to_period("M")란 무엇인가? dt.to_period("M")은 datetime 형식의 데이터를 월 단위로 변환하는 메서드입니다.
#astype("string")란 무엇인가? astype("string")은 데이터 타입을 문자열로 변환하는 메서드입니다.'
#astype이란 무엇인가? astype은 pandas에서 데이터 타입을 변환하는 메서드입니다.

In [90]:
completed_items.head()

,order_item_id,order_id,product_id,quantity,unit_price,line_total,customer_id,order_date,order_status,order_match,product_name,category,product_match,order_month
0,1,1,100,3,102000,306000,123,2026-06-03,completed,both,도서 상품 100,도서,both,2026-06
1,2,1,87,5,25000,125000,123,2026-06-03,completed,both,도서 상품 087,도서,both,2026-06
2,3,1,7,3,142000,426000,123,2026-06-03,completed,both,도서 상품 007,도서,both,2026-06
3,4,1,9,3,193000,579000,123,2026-06-03,completed,both,스포츠 상품 009,스포츠,both,2026-06
4,13,6,83,3,24000,72000,87,2026-04-17,completed,both,전자기기 상품 083,전자기기,both,2026-04

In [91]:
#55. 월별 매출

monthly_sales = (
    completed_items
    .groupby("order_month", as_index=False)
    .agg(
        total_sales=("line_total", "sum"),
        order_count=("order_id", "nunique"),
        customer_count=("customer_id", "nunique"),
        quantity_sold=("quantity", "sum"),
    )
    .sort_values("order_month")
)
display(monthly_sales)

   order_month  total_sales  order_count  customer_count  quantity_sold
0      2025-08      6582000            9               9             59
1      2025-09     16818000           19              19            135
2      2025-10     12895000           15              15            126
3      2025-11     23611000           25              24            235
4      2025-12      8621000           11              11             85
5      2026-01     10935000           14              14            106
6      2026-02     17154000           21              19            155
7      2026-03      9151000           17              15             96
8      2026-04     15536000           17              16            157
9      2026-05     15402000           20              19            156
10     2026-06      8934000           11              11             98
11     2026-07      3128000            4               4             29
12     2026-08       923000            1               1              9

In [92]:
# 56. 고객별 구매 금액

customer_sales = (
    completed_items
    .groupby("customer_id", as_index=False)
    .agg(
        total_sales=("line_total", "sum"),
        order_count=("order_id", "nunique"),
        quantity_sold=("quantity", "sum"),
    )
)

In [93]:
print(customer_sales.head())

   customer_id  total_sales  order_count  quantity_sold
0            3      3178000            2             26
1            4       603000            1              6
2            5      2004000            2             13
3            6      1349000            2             14
4            7      1173000            1              9

In [94]:
print(customer_sales.sort_values("total_sales", ascending=False).head(10))
customer_sales["customer_id"] = customer_sales["customer_id"].astype(int)

    customer_id  total_sales  order_count  quantity_sold
76          117      4100000            5             48
62          102      3996000            4             35
51           83      3880000            4             39
21           30      3590000            5             32
29           40      3523000            4             27
13           20      3191000            2             25
0             3      3178000            2             26
70          111      3153000            3             38
42           66      3093000            4             30
97          147      2990000            2             21

In [95]:
#57. 고객 속성 연결
customer_attributes = customers[
    ["customer_id", "gender", "age", "city"]
].copy()

In [96]:
customer_sales_detail = (
    customer_sales
    .merge(
        customer_attributes,
        on="customer_id",
        how="left",
        validate="one_to_one",
        indicator="customer_match",
    )
    .sort_values("total_sales", ascending=False)
)

In [97]:
display(
    customer_sales_detail["customer_match"].value_counts(
        dropna=False
    )
)
display(customer_sales_detail.head(10))

customer_match
both          100
left_only       0
right_only      0
Name: count, dtype: int64

,customer_id,total_sales,order_count,quantity_sold,gender,age,city,customer_match
76,117,4100000,5,48,F,65,성남,both
62,102,3996000,4,35,M,60,고양,both
51,83,3880000,4,39,F,22,수원,both
21,30,3590000,5,32,F,32,서울,both
29,40,3523000,4,27,M,23,서울,both
13,20,3191000,2,25,F,20,인천,both
0,3,3178000,2,26,F,61,성남,both
70,111,3153000,3,38,F,41,광주,both
42,66,3093000,4,30,F,39,서울,both
97,147,2990000,2,21,M,19,부산,both

In [98]:
# 58. 결과 폴더 생성

output_dir = project_root / "reports" / "chapter04"
output_dir.mkdir(parents=True, exist_ok=True)
print(output_dir)

c:\dev\ai-data-analysis\reports\chapter04

In [99]:
#59. 결과 파일 저장
outputs = {
    "category_sales.csv": category_sales,
    "product_sales.csv": product_sales,
    "monthly_sales.csv": monthly_sales,
    "customer_sales.csv": customer_sales_detail,
}

for file_name, df in outputs.items():
    output_path = output_dir / file_name
    df.to_csv(
        output_path,
        index=False,
        encoding="utf-8-sig",
    )

    print(
        file_name,
        output_path.exists(),
        output_path.stat().st_size,
    )

category_sales.csv True 309
product_sales.csv True 4833
monthly_sales.csv True 413
customer_sales.csv True 3448

In [100]:
#60. 저장 결과 다시 읽기
saved_category_sales = pd.read_csv(
    output_dir / "category_sales.csv"
)

display(saved_category_sales.head())
print(saved_category_sales.shape)

,category,total_sales,order_count,customer_count,quantity_sold,detail_row_count
0,스포츠,31743000,85,67,295,100
1,전자기기,26400000,60,44,259,78
2,생활용품,23915000,65,50,272,83
3,뷰티,23383000,65,53,223,76
4,식품,16573000,36,31,133,42

(7, 6)

In [101]:
#61. 병합 점검 함수
def check_merge_result(
    *,
    name: str,
    left_rows: int,
    merged: pd.DataFrame,
    indicator_column: str,
) -> None:
    print(f"[{name}]")
    print("병합 전 행 수:", left_rows)
    print("병합 후 행 수:", len(merged))
    print(
        merged[indicator_column].value_counts(
            dropna=False
        )
    )

In [102]:
#위의 함수 호출
check_merge_result(
    name="주문상세-주문",
    left_rows=len(order_items_work),
    merged=order_sales,
    indicator_column="order_match",
)

[주문상세-주문]
병합 전 행 수: 766
병합 후 행 수: 766
order_match
both          765
left_only       1
right_only      0
Name: count, dtype: int64

In [103]:
# 62. 집계 합계 검증 함수

def check_total(
    *,
    name: str,
    source_total: float,
    summary_total: float,
) -> None:
    difference = source_total - summary_total

    print(f"[{name}]")
    print("원본 합계:", source_total)
    print("요약 합계:", summary_total)
    print("차이:", difference)

In [104]:

check_total(
    name="카테고리별 매출",
    source_total=completed_items["line_total"].sum(),
    summary_total=category_sales["total_sales"].sum(),
)

[카테고리별 매출]
원본 합계: 149690000
요약 합계: 148990000
차이: 700000

## 검증 항목

| 항목 | 확인 내용 | 자연어 답변 | 결과 |
|---|---|---|---|
| DataFrame | 실제 변수명과 같은가? | 분석에는 `orders`, `order_items`, `products` 세 개의 DataFrame만 사용했습니다. `customers`는 이번 "카테고리별 매출" 분석 범위에 필요하지 않아 로드만 하고 병합에는 쓰지 않았습니다. | ✅ |
| 컬럼 | 실제 컬럼만 사용하는가? | 각 테이블에서 실제 존재하는 컬럼만 사용했습니다. `orders`에서는 `order_id, customer_id, order_date, order_status`, `order_items`에서는 전체 5개 컬럼, `products`에서는 `product_id, product_name, category`만 골라 썼고, 없는 컬럼을 임의로 만들지 않았습니다. | ✅ |
| 상태값 | `completed` 표기가 맞는가? | `orders.order_status`의 실제 값을 확인해보니 `completed`(184건), `cancelled`(64건), `refunded`(52건) 세 가지였고, 철자나 대소문자 오류 없이 `completed`로 정확히 표기되어 있어서 그대로 필터 조건에 사용했습니다. | ✅ |
| 계산식 | `quantity × unit_price`인가? | `line_total` 컬럼은 `order_items_work["quantity"] * order_items_work["unit_price"]`로 계산했습니다. 두 컬럼을 곱한 값 그대로이며 별도 할인·세금 로직은 넣지 않았습니다. | ✅ |
| 분석 범위 | 완료 주문만 포함하는가? | `order_status`로 병합한 뒤 `order_sales[order_sales["order_status"] == "completed"]` 조건으로 걸러서 `completed_sales`를 만들었기 때문에, 취소(cancelled)나 환불(refunded) 주문은 이후 집계에서 전부 제외됩니다. | ✅ |
| 주문 수 | `nunique()`를 사용하는가? | 주문 수는 `order_id`를 단순 개수(count)가 아니라 `nunique()`로 세었습니다. 한 주문에 여러 상품(order_items 행)이 포함될 수 있으므로, 중복 집계를 막기 위해 고유 개수를 쓴 것입니다. | ✅ |
| 병합 키 | 실제 관계와 맞는가? | `order_items.order_id`는 `orders.order_id`를 참조하고, `order_items.product_id`는 `products.product_id`를 참조합니다. 두 관계 모두 "여러 주문상세 행이 하나의 주문/상품에 연결되는" many_to_one 구조와 일치합니다. | ✅ |
| validate | `many_to_one`이 적용되었는가? | 두 번의 `merge()` 호출 모두 `validate="many_to_one"` 옵션을 넣어서, 오른쪽 테이블(`orders`, `products`)의 키가 실제로 유일한지 pandas가 강제로 검사하도록 했습니다. 검증 통과해서 에러 없이 실행됐습니다. | ✅ |
| indicator | 미매칭을 확인하는가? | 두 병합 모두 `indicator="order_match"`, `indicator="product_match"`를 넣어 병합 결과를 both/left_only/right_only로 분류했습니다. 확인 결과 `order_match`는 both 764건 / left_only 0건 / right_only 0건, `product_match`는 both 474건 / left_only 0건 / right_only 0건으로, 매칭 안 된 행이 전혀 없었습니다. | ✅ |
| 행 수 | 병합 전후를 비교하는가? | `order_items_work`가 764행이었는데 `orders`와 병합한 뒤에도 764행 그대로였습니다(1건이 여러 건으로 뻥튀기되지 않았다는 뜻). 완료 주문만 남긴 `completed_sales`가 474행이었고, `products`와 병합한 뒤에도 474행으로 동일했습니다. | ✅ |
| 합계 | 원본과 요약 합계를 비교하는가? | 병합 후 원본 상세 데이터인 `completed_items["line_total"].sum()`은 148,990,000원이었고, 이를 카테고리별로 묶은 `category_sales["total_sales"].sum()`도 동일하게 148,990,000원이었습니다. 두 값이 정확히 일치해서 집계 과정에서 빠지거나 중복된 금액이 없다는 것을 확인했습니다. | ✅ |
| 개인정보 | 원본 고객 정보를 요구하지 않는가? | 이 분석에서는 이름, 이메일, 전화번호, 주소 같은 개인식별정보나 API 키를 전혀 요청하거나 사용하지 않았습니다. 고객을 구분할 때도 `customer_id`라는 숫자 식별자만 집계(고유 고객 수 계산)에 사용했을 뿐, `customers.csv`의 개인정보 컬럼은 아예 불러오지 않았습니다. | ✅ |

# #65 LLM pandas 코드 요청·검증과 최종 점검

In [106]:
# 1) 사전 점검
#사전 점검을 하는 이유는 데이터 분석에서 데이터의 정확성과 일관성을 확인하기 위해서입니다.
# -----------------------------------------
print("orders.order_id 중복:", orders["order_id"].duplicated().sum())
# 근거: 요구사항 6 - order_id가 고유해야 뒤에서 validate="many_to_one"이 성립함을 실행 전에 직접 확인

print("products.product_id 중복:", products["product_id"].duplicated().sum())
# 근거: 요구사항 6 - product_id가 고유해야 validate="many_to_one"이 성립함을 실행 전에 직접 확인

print("order_items.order_id 결측:", order_items["order_id"].isna().sum())
print("order_items.product_id 결측:", order_items["product_id"].isna().sum())
# 근거: 요구사항 6 - 병합 키에 결측치가 있으면 미매칭이 발생하므로 실행 전 확인

print("order_status 고유값:", orders["order_status"].unique())
# 근거: 요구사항 6 - "completed"라는 값이 실제로, 정확한 철자로 존재하는지 실행 전 확인

orders.order_id 중복: 0
products.product_id 중복: 0
order_items.order_id 결측: 0
order_items.product_id 결측: 0
order_status 고유값: <ArrowStringArray>
['completed', 'cancelled', 'refunded']
Length: 3, dtype: str

In [108]:
# 2) line_total 파생 컬럼 생성 (분석 범위: line_total = quantity × unit_price)
# -----------------------------------------
order_items_work = order_items.copy()
order_items_work["line_total"] = (
    order_items_work["quantity"] * order_items_work["unit_price"]
)
# 근거: 분석 범위 요구사항 - "line_total = quantity × unit_price" 정의를 그대로 코드로 구현

In [110]:
# -----------------------------------------
# 3) order_items ↔ orders 병합
# -----------------------------------------
orders_for_merge = orders[
    ["order_id", "customer_id", "order_status"]
].copy()
# 근거: 요구사항 5 - orders 컬럼 중 실제로 존재하는 컬럼(order_id, customer_id, order_status)만 선택.
#       payment_method, order_date 등 이번 요청에 없는 컬럼은 임의로 가져오지 않음

print("병합 전 order_items 행 수:", len(order_items_work))
# 근거: 요구사항 3 - 병합 "전" 행 수 출력

order_sales = order_items_work.merge(
    orders_for_merge,
    on="order_id",
    how="left",
    validate="many_to_one",   # 근거: 요구사항 1 - 이 merge에 validate 사용
    #validate란? - 병합 시 데이터의 일관성을 검증하는 옵션
    indicator="order_match",  # 근거: 요구사항 2 - 이 merge에 indicator 사용 (미매칭 확인용)
    #indicator란 무엇인가? indicator는 병합 시 각 행이 어느 데이터프레임에서 왔는지 나타내는 컬럼을 생성하는 옵션입니다.
)

print("병합 후 order_sales 행 수:", len(order_sales))
# 근거: 요구사항 3 - 병합 "후" 행 수 출력

print(order_sales["order_match"].value_counts(dropna=False))
# 근거: 요구사항 2 - indicator 컬럼(order_match) 값을 실제로 눈으로 확인 (both/left_only/right_only 개수)

unmatched_orders = order_sales[order_sales["order_match"] != "both"]
print("orders와 미매칭된 행 수:", len(unmatched_orders))
# 근거: 요구사항 2 - "both"가 아닌 행 = 미매칭 행을 별도로 걸러내어 개수 확인

병합 전 order_items 행 수: 766
병합 후 order_sales 행 수: 766
order_match
both          765
left_only       1
right_only      0
Name: count, dtype: int64
orders와 미매칭된 행 수: 1

In [111]:
# -----------------------------------------
# 4) 완료(completed) 주문만 필터링
# -----------------------------------------
completed_sales = order_sales[
    order_sales["order_status"] == "completed"
].copy()
# 근거: 분석 범위 요구사항 - "order_status가 completed인 주문만 포함"을 그대로 필터 조건으로 구현

print("완료 주문상세 행 수:", len(completed_sales))

완료 주문상세 행 수: 475

In [112]:
# -----------------------------------------
# 5) completed_sales ↔ products 병합
# -----------------------------------------
products_for_merge = products[
    ["product_id", "category"]
].copy()
# 근거: 요구사항 5 - products 컬럼 중 실제로 필요한 product_id, category만 선택.
#       product_name, price 등 결과 컬럼에 없는 항목은 가져오지 않음

print("병합 전 completed_sales 행 수:", len(completed_sales))
# 근거: 요구사항 3 - 병합 "전" 행 수 출력

completed_items = completed_sales.merge(
    products_for_merge,
    on="product_id",
    how="left",
    validate="many_to_one",     # 근거: 요구사항 1 - 이 merge에도 validate 사용
    indicator="product_match",  # 근거: 요구사항 2 - 이 merge에도 indicator 사용
)

print("병합 후 completed_items 행 수:", len(completed_items))
# 근거: 요구사항 3 - 병합 "후" 행 수 출력

print(completed_items["product_match"].value_counts(dropna=False))
# 근거: 요구사항 2 - indicator 컬럼(product_match) 값을 실제로 눈으로 확인

unmatched_products = completed_items[completed_items["product_match"] != "both"]
print("products와 미매칭된 행 수:", len(unmatched_products))
# 근거: 요구사항 2 - "both"가 아닌 행 = 미매칭 행을 별도로 걸러내어 개수 확인

병합 전 completed_sales 행 수: 475
병합 후 completed_items 행 수: 475
product_match
both          474
left_only       1
right_only      0
Name: count, dtype: int64
products와 미매칭된 행 수: 1

## products와 미매칭된 행 수가 있는 이유
이전 수업에서 고아 데이터를 추가 해놓은 것 때문.

In [113]:
# -----------------------------------------
# 6) 카테고리별 매출 집계
# -----------------------------------------
category_sales = (
    completed_items
    .groupby("category", as_index=False)
    .agg(
        total_sales=("line_total", "sum"),
        order_count=("order_id", "nunique"),
        customer_count=("customer_id", "nunique"),
        quantity_sold=("quantity", "sum"),
    )
    # 근거: 요구사항 5 - "원하는 결과 컬럼" 5개(category, total_sales, order_count,
    #       customer_count, quantity_sold)만 정확히 생성. 요청에 없던 detail_row_count 등은 추가하지 않음
    .sort_values("total_sales", ascending=False)
)

print(category_sales)

  category  total_sales  order_count  customer_count  quantity_sold
3      스포츠     31743000           85              67            295
5     전자기기     26400000           60              44            259
2     생활용품     23915000           65              50            272
1       뷰티     23383000           65              53            223
4       식품     16573000           36              31            133
0       도서     16389000           52              46            149
6       패션     10587000           33              27            111

In [114]:
# -----------------------------------------
# 7) 카테고리 합계 vs 완료 주문 전체 합계 비교
# -----------------------------------------
category_total = category_sales["total_sales"].sum()
completed_total = completed_items["line_total"].sum()

print("카테고리 합계:", category_total)
print("완료 주문 전체 합계:", completed_total)
print("일치 여부:", category_total == completed_total)
# 근거: 요구사항 4 - "카테고리 합계와 완료 주문 전체 합계를 비교"를 두 값을 직접 비교하는 코드로 구현.
#       True가 나오면 카테고리별로 쪼개도 전체 매출액이 새지 않았다는 뜻

카테고리 합계: 148990000
완료 주문 전체 합계: 149690000
일치 여부: False

# 미매칭 진단&수정

In [115]:
# -----------------------------------------
# 진단 1) order_items ↔ orders 미매칭 원인
# -----------------------------------------
print("orders 미매칭 행 상세:")
display(unmatched_orders)   # order_id, product_id 등 실제 값 확인

unmatched_order_id = unmatched_orders["order_id"].iloc[0]
print("미매칭된 order_id 값:", unmatched_order_id, "| dtype:", type(unmatched_order_id))

# 이 order_id가 orders 테이블에 정말 없는지 확인
print("orders에 이 order_id 존재 여부:", unmatched_order_id in orders["order_id"].values)

# dtype 비교
print("order_items.order_id dtype:", order_items["order_id"].dtype)
print("orders.order_id dtype:", orders["order_id"].dtype)

orders 미매칭 행 상세:

,order_item_id,order_id,product_id,quantity,unit_price,line_total,customer_id,order_status,order_match
764,789,320,67,5,32000,160000,NaN,NaN,left_only

미매칭된 order_id 값: 320 | dtype: <class 'numpy.int64'>
orders에 이 order_id 존재 여부: False
order_items.order_id dtype: int64
orders.order_id dtype: int64

In [116]:
# -----------------------------------------
# 진단 2) completed_sales ↔ products 미매칭 원인
# -----------------------------------------
print("\nproducts 미매칭 행 상세:")
display(unmatched_products)   # product_id 등 실제 값 확인

unmatched_product_id = unmatched_products["product_id"].iloc[0]
print("미매칭된 product_id 값:", unmatched_product_id, "| dtype:", type(unmatched_product_id))

print("products에 이 product_id 존재 여부:", unmatched_product_id in products["product_id"].values)

print("order_items.product_id dtype:", order_items["product_id"].dtype)
print("products.product_id dtype:", products["product_id"].dtype)

products 미매칭 행 상세:

,order_item_id,order_id,product_id,quantity,unit_price,line_total,customer_id,order_status,order_match,category,product_match
474,763,299,108,4,175000,700000,135.0,completed,both,NaN,left_only

미매칭된 product_id 값: 108 | dtype: <class 'numpy.int64'>
products에 이 product_id 존재 여부: False
order_items.product_id dtype: int64
products.product_id dtype: int64

In [121]:
#미매칭 제외 코드
order_sales_clean = order_sales[order_sales["order_match"] == "both"]
completed_items_clean = completed_items[completed_items["product_match"] == "both"]

print("제외 건수:", (order_sales["order_match"] != "both").sum(),
      (completed_items["product_match"] != "both").sum())

제외 건수: 1 1

In [120]:
# =========================================
# 최종 확인 코드 (변경된 부분만 주석 표시)
# =========================================

# 1) line_total 생성 (동일)
order_items_work = order_items.copy()
order_items_work["line_total"] = (
    order_items_work["quantity"] * order_items_work["unit_price"]
)

# 2) order_items ↔ orders 병합 + 검증 (동일)
orders_for_merge = orders[["order_id", "customer_id", "order_status"]].copy()

print("병합 전 order_items 행 수:", len(order_items_work))

order_sales = order_items_work.merge(
    orders_for_merge,
    on="order_id",
    how="left",
    validate="many_to_one",
    indicator="order_match",
)

print("병합 후 order_sales 행 수:", len(order_sales))
print(order_sales["order_match"].value_counts(dropna=False))

# [변경됨] orders 미매칭을 명시적으로 제외하는 단계 추가
# (결과값 자체에는 영향 없음 — order_id 320은 order_status가 NaN이 되어
#  아래 completed 필터에서 자동으로 걸러지기 때문. 다만 "몇 건이 왜 빠졌는지"
#  기록을 남기기 위해 감사(audit) 목적으로 추가함)
order_match_excluded = (order_sales["order_match"] != "both").sum()
order_sales_clean = order_sales[order_sales["order_match"] == "both"]
print("orders 미매칭 제외 건수:", order_match_excluded)

# 4) 완료 주문만 필터링
# [변경됨] 필터링 대상이 order_sales → order_sales_clean 으로 바뀜
#          (위에서 이미 걸러졌기 때문에 실제 결과는 동일)
completed_sales = order_sales_clean[
    order_sales_clean["order_status"] == "completed"
].copy()
print("완료 주문상세 행 수:", len(completed_sales))

# 5) completed_sales ↔ products 병합 + 검증 (동일)
products_for_merge = products[["product_id", "category"]].copy()

print("병합 전 completed_sales 행 수:", len(completed_sales))

completed_items = completed_sales.merge(
    products_for_merge,
    on="product_id",
    how="left",
    validate="many_to_one",
    indicator="product_match",
)

print("병합 후 completed_items 행 수:", len(completed_items))
print(completed_items["product_match"].value_counts(dropna=False))

# [변경됨] products 미매칭을 실제로 제외하는 단계 추가
# (이전 코드는 확인만 하고 제외하지 않았음 → 이번엔 completed_items_clean 생성)
product_match_excluded = (completed_items["product_match"] != "both").sum()
completed_items_clean = completed_items[completed_items["product_match"] == "both"]
print("products 미매칭 제외 건수:", product_match_excluded)

# 7) 카테고리별 매출 집계
# [변경됨] 집계 대상이 completed_items → completed_items_clean 으로 바뀜
category_sales = (
    completed_items_clean
    .groupby("category", as_index=False)
    .agg(
        total_sales=("line_total", "sum"),
        order_count=("order_id", "nunique"),
        customer_count=("customer_id", "nunique"),
        quantity_sold=("quantity", "sum"),
    )
    .sort_values("total_sales", ascending=False)
)
print(category_sales)

# 8) 최종 일치 여부 확인
category_total = category_sales["total_sales"].sum()

# [핵심 변경 지점] ★ True/False를 가른 실제 원인 ★
# 이전: completed_items["line_total"].sum()          ← 미매칭(orphan) 포함
# 지금: completed_items_clean["line_total"].sum()     ← 미매칭 제외한 정제본
# category_sales는 groupby가 NaN 카테고리를 자동으로 빼고 계산하므로,
# 비교 대상도 반드시 같은 정제본(completed_items_clean) 기준이어야 True가 됨
completed_total = completed_items_clean["line_total"].sum()

print("\n===== 최종 검증 결과 =====")
print("카테고리 합계:", category_total)
print("완료 주문 합계(정제 후):", completed_total)
print("일치 여부:", category_total == completed_total)

병합 전 order_items 행 수: 766
병합 후 order_sales 행 수: 766
order_match
both          765
left_only       1
right_only      0
Name: count, dtype: int64
orders 미매칭 제외 건수: 1
완료 주문상세 행 수: 475
병합 전 completed_sales 행 수: 475
병합 후 completed_items 행 수: 475
product_match
both          474
left_only       1
right_only      0
Name: count, dtype: int64
products 미매칭 제외 건수: 1
  category  total_sales  order_count  customer_count  quantity_sold
3      스포츠     31743000           85              67            295
5     전자기기     26400000           60              44            259
2     생활용품     23915000           65              50            272
1       뷰티     23383000           65              53            223
4       식품     16573000           36              31            133
0       도서     16389000           52              46            149
6       패션     10587000           33              27            111

===== 최종 검증 결과 =====
카테고리 합계: 148990000
완료 주문 합계(정제 후): 148990000
일치 여부: True

# 65. LLM 코드 검증표

**분석 대상**: 완료 주문 기준 카테고리별 매출 계산 (category_sales)
**검증 일자**: 2026-08-11

| 검증 항목 | 확인 내용 | 결과 |
|---|---|---|
| DataFrame | 실제 변수명과 같은가? |orders, order_items, products 그대로 사용 |
| 컬럼 | 실제 컬럼만 사용하는가? | 요청에 없던 컬럼(payment_method, order_date, product_name, price 등) 미사용 |
| 상태값 | completed 표기가 맞는가? | orders["order_status"].unique() 로 실제 값 확인 후 필터링 |
| 계산식 | quantity × unit_price 인가? | line_total = quantity * unit_price 로 구현 |
| 분석 범위 | 완료 주문만 포함하는가? | order_status == "completed" 필터 적용 |
| 주문 수 | nunique()를 사용하는가? | order_count=("order_id", "nunique") |
| 병합 키 | 실제 관계와 맞는가? | order_items.order_id→orders.order_id, order_items.product_id→products.product_id |
| validate | many_to_one이 적용되었는가? | 두 merge 모두 validate="many_to_one" 적용 |
| indicator | 미매칭을 확인하는가? | order_match, product_match로 확인, orphan 2건(order_id 320, product_id 108) 발견 |
| 행 수 | 병합 전후를 비교하는가? | 각 merge 직전/직후 len() 출력하여 비교 |
| 합계 | 원본과 요약 합계를 비교하는가? | 미매칭 2건 제외 후 category_total == completed_total → True 확인 |
| 개인정보 | 원본 고객 정보를 요구하지 않는가? | customer_id만 사용, 이름/이메일/전화번호/주소 미사용 |

---

## 참고: 발견된 이슈 및 처리 내역

| 이슈 | 원인 | 처리 |
|---|---|---|
| order_items ↔ orders 미매칭 1건 | order_id 320이 orders 테이블에 없음 (orphan, dtype 문제 아님) | order_match == "both"만 사용 |
| completed_sales ↔ products 미매칭 1건 | product_id 108이 products 테이블에 없음 (orphan, dtype 문제 아님) | product_match == "both"만 사용 |
| 초기 합계 불일치 (False) | groupby가 NaN 카테고리를 자동 제외하는데, 비교 대상은 미매칭 포함 데이터였음 | 양쪽 모두 정제된 데이터(completed_items_clean) 기준으로 통일 → True |